// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EquipmentController from "./equipment_controller.js"
application.register("equipment", EquipmentController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import SafeAuditController from "./safe_audit_controller.js"
application.register("safe-audit", SafeAuditController)

import ShowSignatureController from "./show_signature_controller.js"
application.register("show-signature", ShowSignatureController)

import SignatureController from "./signature_controller.js"
application.register("signature", SignatureController)
