// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AttendController from "./attend_controller.js"
application.register("attend", AttendController)

import BackgroundController from "./background_controller.js"
application.register("background", BackgroundController)

import CurriculumController from "./curriculum_controller.js"
application.register("curriculum", CurriculumController)

import DocumentController from "./document_controller.js"
application.register("document", DocumentController)

import EquipmentController from "./equipment_controller.js"
application.register("equipment", EquipmentController)

import FoodSafetyController from "./food_safety_controller.js"
application.register("food-safety", FoodSafetyController)

import FormController from "./form_controller.js"
application.register("form", FormController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import NewHireController from "./new_hire_controller.js"
application.register("new-hire", NewHireController)

import SafeAuditController from "./safe_audit_controller.js"
application.register("safe-audit", SafeAuditController)

import ShopController from "./shop_controller.js"
application.register("shop", ShopController)

import ShowSignatureController from "./show_signature_controller.js"
application.register("show-signature", ShowSignatureController)

import SignatureController from "./signature_controller.js"
application.register("signature", SignatureController)

import StudentController from "./student_controller.js"
application.register("student", StudentController)

import ToggleController from "./toggle_controller.js"
application.register("toggle", ToggleController)
