class CreateMocs < ActiveRecord::Migration[7.0]
  def change
    create_table :mocs do |t|
      t.references :organization, null: false, foreign_key: true
      t.references :store, null: false, foreign_key: true
      t.date :moc_date
      t.time :moc_time
      t.string :ops_score
      t.string :service_score
      t.string :quality_score
      t.string :cleanliness_score
      t.boolean :verified
      t.string :dt_cars_target_1
      t.string :dt_cars_target_2
      t.string :dt_cars_target_3
      t.string :dt_cars_actual_1
      t.string :dt_cars_actual_2
      t.string :dt_cars_actual_3
      t.string :dt_oepe_target_1
      t.string :dt_oepe_target_2
      t.string :dt_oepe_target_3
      t.string :dt_oepe_actual_1
      t.string :dt_oepe_actual_2
      t.string :dt_oepe_actual_3
      t.string :di_guest_target_1
      t.string :di_guest_target_2
      t.string :di_guest_target_3
      t.string :di_guest_actual_1
      t.string :di_guest_actual_2
      t.string :di_guest_actual_3
      t.string :di_time_target_1
      t.string :di_time_target_2
      t.string :di_time_target_3
      t.string :di_time_actual_1
      t.string :di_time_actual_2
      t.string :di_time_actual_3
      t.string :add_target_1
      t.string :add_target_2
      t.string :add_target_3
      t.string :add_actual_1
      t.string :add_actual_2
      t.string :add_actual_3
      t.string :q1
      t.string :q2
      t.string :q3
      t.string :q4
      t.string :q5
      t.string :q6
      t.string :q7
      t.string :q8
      t.string :q9
      t.string :q10
      t.string :q11
      t.string :q12
      t.string :q13
      t.string :q14
      t.string :q15
      t.string :q16
      t.string :q17
      t.string :q18
      t.string :q19
      t.string :q20
      t.string :q21
      t.string :q22
      t.string :q23
      t.string :q24
      t.string :q25
      t.string :q26
      t.string :q27
      t.string :q28
      t.string :q29
      t.string :q30
      t.string :q31
      t.string :q32
      t.string :q33
      t.string :q34
      t.string :q35
      t.string :q36
      t.string :q37
      t.string :q38
      t.string :q39
      t.string :q40
      t.string :q41
      t.string :q42
      t.string :q43
      t.string :q44
      t.string :q45
      t.string :q46
      t.string :q47
      t.string :q48
      t.string :q49
      t.string :q50
      t.string :q51
      t.string :q52
      t.string :q53
      t.string :q54
      t.string :q55
      t.string :q56
      t.string :q57
      t.string :q58
      t.string :q59
      t.string :q60
      t.string :q61
      t.string :q62
      t.string :q63
      t.string :q64
      t.string :opstotal
      t.string :qualitytotal
      t.string :servicetotal
      t.string :cleantotal
      t.string :signature
      t.string :preshiftsuccess
      t.string :servicesuccess
      t.string :grillsuccess
      t.string :cleansuccess
      t.string :postshiftsuccess
      t.string :very_good_comments
      t.string :more_practice_comments

      t.timestamps
    end
  end
end
